プレイヤー処理のベース作成
vm-t-yui/mochi-int1 pull request #45
Opened 2019-08-15 14:49 UTC by tricore-as05

プレイヤー処理のベース作成し、そのベースを継承しているクラスのoverride関数を一気に呼び出すように変更しました。
・PlayerActionBase.cs
プレイヤーの処理のベースクラス
・PlayerActionCaller.cs
ベースを継承したクラスのoverride関数を呼び出すクラス
・PlayerController.cs
ベースを継承した形に変更
・TouchController.cs
アニメーションが終わるまで入力を取らないようにしていたが、それを削除

2019-08-16 04:42 UTC, tr-t-mitsumaru requested changes
モチかウサギかでプレイヤー側の別々のアニメーションを再生できるようにベースを作ったのかと思ったが、`PlayerActionBase`を継承しているクラスは`PlayerController`だけみたいなのでそうではないのかな。
いくつか分からない点があるのでRequest changesで。

2019-08-16 04:42 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Player/PlayerActionBase.cs
> +public abstract class PlayerActionBase : MonoBehaviour
[Q]
プレイヤーであるモチマンはゲーム内で１体しか存在しないのに、ベースを作った意図が分からない。
なぜ、ベースを作ったのかを教えてほしい。
ちなみに、僕がベースを作った意図はモチだろうがウサギだろうが同じ関数を呼ぶことで、その種類に応じた処理を行ってもらうため。

2019-08-16 04:42 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Player/PlayerActionCaller.cs
> +    PlayerActionBase[] actionBase;
[Q]
`PlayerActionBase`の配列がシリアライズ化されてるということは、もしかしてウサギとモチに`PlayerActionBase`を持たせて、その参照をこの配列にセットするってこと？

2019-08-17 14:40 UTC, tr-t-mitsumaru approved these changes
問題なし。ありがとう。

2019-08-18 08:37 UTC, tricore-as04 approved these changes
大丈夫やと思う

2019-08-18 16:26 UTC, merged