プレイヤー関連 + タイマーのスクリプト
vm-t-yui/mochi-int1 pull request #5
Opened 2019-07-24 08:57 UTC by tricore-as05

プレイヤー関連 + タイマーのスクリプトです。
見て欲しいのは、
PlayerAnimationController.cs -> プレイヤーのアニメーションのクラス
PlayerController.cs -> プレイヤーの動きの管理クラス
Timer.cs -> タイマークラス
TouchController.cs -> 入力管理クラス
です。

2019-07-24 09:55 UTC, vm-t-yui requested changes

2019-07-24 09:55 UTC, vm-t-yui commented on Assets/MyGameAssets/Script/PlayerAnimationController.cs
> +/// </summary>
[nits]
何から呼ばれるのか紛らわしいので書いてほしいなあ
AnimationEventなのか、だれか持つのか…

2019-07-24 09:55 UTC, vm-t-yui commented on Assets/MyGameAssets/Script/PlayerAnimationController.cs
> +/// </summary>
下見れば分かるけどこのファイル見ただけで分かる形が理想

2019-07-24 09:55 UTC, vm-t-yui commented on Assets/MyGameAssets/Script/PlayerController.cs
> +
[nits]
PlayerAnimationController.AnimKind長いからusingしてもよさそう

2019-07-24 09:55 UTC, vm-t-yui commented on Assets/MyGameAssets/Script/Timer.cs
> +            float nowTime = seconds - Time.time;
[nits]
Time.timeよりはTime.timeSinceLevelLoadedのほうがオーバーフローなくて確実

2019-07-24 09:55 UTC, vm-t-yui commented on Assets/MyGameAssets/Script/TouchController.cs
> +	bool isSwipe = false;               //スワイプフラグ
[MUST]
謎のタブ

2019-07-25 05:06 UTC, tricore-as04 approved these changes
よいと思われる

2019-07-25 05:23 UTC, tr-t-mitsumaru approved these changes

2019-07-26 01:07 UTC, merged